name: Scratch Reputation System Tracker

on:
  schedule:
    # --- BAN NGÀY (Quét mỗi 30 phút vào phút 13 và 43) ---
    # Giờ VN: 6h sáng -> 10h tối (Tương đương UTC: 23h và từ 0h đến 15h)
    - cron: '13,43 23,0-15 * * *'
    
    # --- BAN ĐÊM (Quét chậm hơn: 2 tiếng/lần vào phút 13) ---
    # Giờ VN: 11h đêm, 1h, 3h, 5h sáng (Tương đương UTC: 16, 18, 20, 22)
    - cron: '13 16,18,20,22 * * *'

  # Cho phép bạn bấm chạy thủ công trên GitHub để test
  workflow_dispatch: 

# Ngăn 2 task chạy song song đè lên file database.json nếu task trước bị kẹt
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write # Cấp quyền cho Action ghi đè lại file database.json

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python main.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto-update database [skip ci]"
          file_pattern: 'database.json'