name: Scratch Reputation System Tracker

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    # Chạy vào các giờ UTC
    - cron: '17,47 1-15 * * *'
  # Cho phép bạn bấm chạy thủ công trên GitHub để test
  workflow_dispatch: 

permissions:
  contents: write # Cấp quyền cho Action ghi đè lại file database.json

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python main.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update database [skip ci]"
          file_pattern: 'database.json'